# Generated by Django 6.0.6 on 2026-08-07 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
            ],
            options={
                'ordering': ['ciclo_lectivo__nombre', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='CicloLectivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Anio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anios', to='Asistencia.carrera')),
            ],
            options={
                'ordering': ['carrera__nombre', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=150)),
                ('nombre', models.CharField(max_length=150)),
                ('dni', models.CharField(max_length=8, unique=True)),
                ('anio_actual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alumnos', to='Asistencia.anio')),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='alumnos', to='Asistencia.carrera')),
            ],
            options={
                'ordering': ['apellido', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='carrera',
            name='ciclo_lectivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carreras', to='Asistencia.ciclolectivo'),
        ),
        migrations.CreateModel(
            name='Inscripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='Asistencia.alumno')),
                ('ciclo_lectivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='Asistencia.ciclolectivo')),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('P', 'Presente'), ('A', 'Ausente'), ('T', 'Tarde'), ('J', 'Justificada')], default='P', max_length=1)),
                ('inscripcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencias', to='Asistencia.inscripcion')),
            ],
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('anio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materias', to='Asistencia.anio')),
            ],
            options={
                'ordering': ['anio__carrera__nombre', 'anio__nombre', 'nombre'],
            },
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscripciones', to='Asistencia.materia'),
        ),
        migrations.AddConstraint(
            model_name='anio',
            constraint=models.UniqueConstraint(fields=('carrera', 'nombre'), name='anio_unico_por_carrera'),
        ),
        migrations.AddConstraint(
            model_name='carrera',
            constraint=models.UniqueConstraint(fields=('ciclo_lectivo', 'nombre'), name='carrera_unica_por_ciclo'),
        ),
        migrations.AddConstraint(
            model_name='asistencia',
            constraint=models.UniqueConstraint(fields=('inscripcion', 'fecha'), name='asistencia_unica'),
        ),
        migrations.AddConstraint(
            model_name='materia',
            constraint=models.UniqueConstraint(fields=('anio', 'nombre'), name='materia_unica_por_anio'),
        ),
        migrations.AddConstraint(
            model_name='inscripcion',
            constraint=models.UniqueConstraint(fields=('alumno', 'materia', 'ciclo_lectivo'), name='inscripcion_unica'),
        ),
    ]
