# Generated by Django 6.0.6 on 2026-08-08 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Asistencia', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumno',
            name='anio_actual',
        ),
    ]
